name: Test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Install @octokit/auth-app
      run: |
        npm install @octokit/auth-app
    - name: Get token using github-script
      id: format-inputs
      uses: actions/github-script@v5
      with:
        script: |
          console.log(github.constructor)
          
          // Login as GitHub App
          const { Octokit } = __original_require__("@octokit/rest");
          const { createAppAuth } = __original_require__("@octokit/auth-app");

          const appOctokit = new Octokit({
            authStrategy: createAppAuth,
            auth: {
              appId: '${{ secrets.app-issueops-id }}',
              privateKey: '${{ secrets.app-issueops-pem }}',
              // optional: this will make appOctokit authenticate as app (JWT)
              //           or installation (access token), depending on the request URL
              installationId: '${{ secrets.app-installation-id }}'
            },
          });
          const { token } = await appOctokit.auth({
            type: "installation",
            // defaults to `options.auth.installationId` set in the constructor
            installationId: '${{ secrets.app-installation-id }}'
          });
          core.setSecret(token)
          console.log(token)
