name: Test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Get token using github-script
      uses: actions/github-script@v5
      with:
        script: |
          const { token } = await github.rest.apps.createInstallationAccessToken({
            installation_id: '${{ secrets.APP_ISSUEOPS_INSTALL_ID }}'
          });
          console.log(token)
    - name: Install @octokit/rest & @octokit/auth-app
      run: |
        npm install @octokit/rest @octokit/auth-app
    - name: Get token using github-script
      id: format-inputs
      uses: actions/github-script@v5
      with:
        script: |
          // Login as GitHub App
          // https://octokit.github.io/rest.js/v18#authentication
          const { Octokit } = require("@octokit/rest");
          const { createAppAuth } = require("@octokit/auth-app");

          const appOctokit = new Octokit({
            authStrategy: createAppAuth,
            auth: {
              appId: '${{ secrets.APP_ISSUEOPS_ID }}',
              privateKey: Buffer.from('${{ secrets.APP_ISSUEOPS_PEM }}', 'base64').toString(),
              // optional: this will make appOctokit authenticate as app (JWT)
              //           or installation (access token), depending on the request URL
              installationId: '${{ secrets.APP_ISSUEOPS_INSTALL_ID }}'
            },
          });
          const { token } = await appOctokit.auth({
            type: "installation",
            // defaults to `options.auth.installationId` set in the constructor
            installationId: '${{ secrets.APP_ISSUEOPS_INSTALL_ID }}'
          });
          //core.setSecret(token) // Not needed - seems set by octokit
          console.log(token)
